server:
  port: 8080
  servlet:
    context-path: /

#数据源配置
spring:
  datasource:
    url: jdbc:mysql://139.196.19.64:3306/vin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: wgzn@2021
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    # 连接超时时间（毫秒）
    #timeout: 1000
      host: 127.0.0.1
      port: 6379
      password:
      jedis:
        pool:
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1
          # 连接池中的最大空闲连接
          max-idle: 500
          # 连接池中的最小空闲连接
          min-idle: 0
      lettuce:
        shutdown-timeout: 0

# xml文件在resource目录下
#mybatis:
#  mapper-locations: classpath:mapper/*.xml

#
# xml文件在java目录下
mybatis-plus:
  mapper-locations: com/wb/bench/mapper/xml/*.xml
  #开启sql打印
  configuration:
    log-impl:  org.apache.ibatis.logging.stdout.StdOutImpl
    #启动结果集自动映射
    auto-mapping-behavior: partial
    #驼峰映射
    map-underscore-to-camel-case: true

