server:
  port: 8081
  servlet:
    context-path: /

#数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


# xml文件在resource目录下
#mybatis:
#  mapper-locations: classpath:mapper/*.xml

#
# xml文件在java目录下
mybatis-plus:
  mapper-locations: com/wb/bench/mapper/xml/*.xml
  #开启sql打印
  configuration:
    log-impl:  org.apache.ibatis.logging.stdout.StdOutImpl
    #启动结果集自动映射
    auto-mapping-behavior: partial
    #驼峰映射
    map-underscore-to-camel-case: true